server:
  port: 8080

spring:
  application:
    name: mail-app
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./test
    username: ${DS_USERNAME:root}
    password: ${DS_PASSWORD:12345678}
    driver-class-name: org.h2.Driver



